### PR TITLE
11.21

### PR DESCRIPTION
**Pull request by ziquanli2020**
11.21

### CODE REVIEW

**Comment by ziquanli2020** [comment]
wrong operation

**Comment by sahilrajput03** [comment]
@LiamLi2020  What happened? Do the repo work now .., I remember recently I tried to run this project but due to some failure it couldn't run at all. 

I see ur repo @ https://github.com/LiamLi2020/create-app/tree/11.21 .., does it work?

**Comment by ziquanli2020** [comment]
> @LiamLi2020 What happened? Do the repo work now .., I remember recently I tried to run this project but due to some failure it couldn't run at all.
> 
> I see ur repo @ https://github.com/LiamLi2020/create-app/tree/11.21 .., does it work?

It works. I just check the log, and heroku documentation shows me how to configure the node version in heroku. Finally it works.

**Comment by sahilrajput03** [comment]
can you share the heroku url?.

**Comment by ziquanli2020** [comment]
> 



> can you share the heroku url?.

https://devcenter.heroku.com/articles/troubleshooting-node-deploys#compare-node-and-npm-versions
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

**Comment by sahilrajput03** [comment]
i mean the url u deployed the project to.. 😅

**Comment by ziquanli2020** [comment]
> i mean the url u deployed the project to.. sweat_smile
ok ok
https://fullstack11repo2liam.herokuapp.com/

**Comment by sahilrajput03** [comment]
Thanks., so will u create a pr now?.

**Comment by ziquanli2020** [comment]
> 

Do you mean creating a pr to this repository?
I guess no... This repository seems it is not maintained any more. I just google the questions when I met the questions yesterday. I do not even remember what to fix now...

**Comment by sahilrajput03** [comment]
react, react-dom, webpack and other dependent libraries like hot-loader and many more needs to be updated as well. I think I am gonna use nextjs for backend+frontend solutions with react.

**Pull request closed without merging**
